name: Deploy to Vercel

on:
  push:
    branches:
      - main   # Atau 'master' jika repo kamu masih pakai branch itu
  workflow_dispatch:     # Memungkinkan deploy manual dari GitHub UI

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          org: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
          vercel-api-url: 'https://api.vercel.com' 